version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - go
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      grpc-protobuf:
        patterns:
          - "google.golang.org/grpc*"
          - "google.golang.org/protobuf*"
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - docker
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
