package registry

import (
	"bytes"
	"errors"
	"fmt"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// ClaimInput is the validated form payload from POST /claim.
//
// It maps to the schema in `schemas/app.schema.json` of the registry repo.
// The form in the brief offers `images.<workload>.{repository,tag}` selects
// — those are kept on the form for ergonomics but folded into the existing
// `repo` block (we keep the spec, not invent fields the schema rejects).
type ClaimInput struct {
	Slug string

	OwnerTechnical      string
	OwnerOrganizational string

	RepoURL string

	HasBackend  bool
	HasFrontend bool

	BackendMemoryLimit  string
	BackendCPULimit     string
	FrontendMemoryLimit string
	FrontendCPULimit    string

	StagingHost string
	ProdHost    string

	// Optional metadata captured from the form but stored only in the PR body.
	BackendImageRepo  string
	BackendImageTag   string
	FrontendImageRepo string
	FrontendImageTag  string
}

// Validate enforces the constraints from the JSON schema we can reasonably
// check server-side (regex on slug, host format, resource-quantity regex).
func (c *ClaimInput) Validate(reserved *ReservedSlugs) error {
	if !SlugRegex.MatchString(c.Slug) {
		return fmt.Errorf("slug %q does not match ^[a-z][a-z0-9-]{2,30}[a-z0-9]$", c.Slug)
	}

	if reserved.IsReserved(c.Slug) {
		return fmt.Errorf("slug %q is reserved", c.Slug)
	}

	if c.OwnerTechnical == "" || c.OwnerOrganizational == "" {
		return errors.New("both technical and organizational owners are required")
	}

	if !strings.HasPrefix(c.RepoURL, "https://") {
		return fmt.Errorf("repo.url must start with https://, got %q", c.RepoURL)
	}

	if !memoryRegex.MatchString(c.BackendMemoryLimit) {
		return fmt.Errorf("backend memory limit %q invalid", c.BackendMemoryLimit)
	}

	if !memoryRegex.MatchString(c.FrontendMemoryLimit) {
		return fmt.Errorf("frontend memory limit %q invalid", c.FrontendMemoryLimit)
	}

	if !cpuRegex.MatchString(c.BackendCPULimit) {
		return fmt.Errorf("backend cpu limit %q invalid", c.BackendCPULimit)
	}

	if !cpuRegex.MatchString(c.FrontendCPULimit) {
		return fmt.Errorf("frontend cpu limit %q invalid", c.FrontendCPULimit)
	}

	if c.StagingHost == "" || c.ProdHost == "" {
		return errors.New("staging.host and prod.host are required")
	}

	return nil
}

// ToApp turns a validated ClaimInput into a registry.App ready to render.
func (c *ClaimInput) ToApp() *App {
	return &App{
		APIVersion: "platform.meko.dev/v1",
		Kind:       "App",
		Slug:       c.Slug,
		Owners: Owners{
			Technical:      c.OwnerTechnical,
			Organizational: c.OwnerOrganizational,
		},
		Repo: Repo{
			URL:           c.RepoURL,
			DefaultBranch: "main",
			HasBackend:    c.HasBackend,
			HasFrontend:   c.HasFrontend,
		},
		Stages: Stages{
			Staging: Stage{
				Host:             c.StagingHost,
				AutoDeployBranch: "main",
			},
			Prod: Stage{
				Host:                   c.ProdHost,
				AutoDeployBranch:       "release",
				RequireManualPromotion: true,
			},
		},
		Resources: Resources{
			Backend: ResourceBlock{
				MemoryLimit: c.BackendMemoryLimit,
				CPULimit:    c.BackendCPULimit,
				Replicas:    1,
			},
			Frontend: ResourceBlock{
				MemoryLimit: c.FrontendMemoryLimit,
				CPULimit:    c.FrontendCPULimit,
				Replicas:    1,
			},
		},
		Features: Features{
			IngressAuth: "none",
		},
		CreatedAt: time.Now().UTC().Format("2006-01-02"),
	}
}

// RenderYAML marshals an App to indented YAML.
func (a *App) RenderYAML() ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by ewws-platform-ui\n")
	buf.WriteString("# Schema: ../schemas/app.schema.json\n\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)

	if err := enc.Encode(a); err != nil {
		return nil, fmt.Errorf("encode app: %w", err)
	}

	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("close encoder: %w", err)
	}

	return buf.Bytes(), nil
}

// MemoryOptions / CPUOptions / HostOptions are the dropdown choices the
// claim form offers. Keep them in code so the form and the validator stay
// in lockstep.
var (
	MemoryOptions = []string{"128Mi", "256Mi", "512Mi", "1Gi", "2Gi"}
	CPUOptions    = []string{"100m", "250m", "500m", "1", "2"}
)

var (
	memoryRegex = mustCompileSchema(`^[0-9]+(\.[0-9]+)?(Ki|Mi|Gi|Ti|K|M|G|T)?$`)
	cpuRegex    = mustCompileSchema(`^[0-9]+(\.[0-9]+)?m?$`)
)
